START "Starting bot 1" "C:\Users\Evan Sparano\Documents\GitHub\galcon-alphazero\gbots\startDevBot1.bat"
timeout /t 5 /nobreak > NUL
START "Starting bot 2" "C:\Users\Evan Sparano\Documents\GitHub\galcon-alphazero\gbots\startDevBot2.bat"
timeout /t 5 /nobreak > NUL
START "Starting bot 3" "C:\Users\Evan Sparano\Documents\GitHub\galcon-alphazero\gbots\startDevBot3.bat"
timeout /t 5 /nobreak > NUL
START "Starting bot 4" "C:\Users\Evan Sparano\Documents\GitHub\galcon-alphazero\gbots\startDevBot4.bat"
timeout /t 5 /nobreak > NUL
START "Starting bot 5" "C:\Users\Evan Sparano\Documents\GitHub\galcon-alphazero\gbots\startDevBot5.bat"
timeout /t 5 /nobreak > NUL
START "Starting bot 6" "C:\Users\Evan Sparano\Documents\GitHub\galcon-alphazero\gbots\startDevBot6.bat"
timeout /t 5 /nobreak > NUL
START "Starting bot 7" "C:\Users\Evan Sparano\Documents\GitHub\galcon-alphazero\gbots\startDevBot7.bat"
timeout /t 5 /nobreak > NUL
START "Starting bot 8" "C:\Users\Evan Sparano\Documents\GitHub\galcon-alphazero\gbots\startDevBot8.bat"